const foodList = [
    "Chicken Nuggets", "French Fries", "Cheese Pizza", "Pepperoni Pizza",
    "Restaurant-Style Macaroni and Cheese", "Hamburgers", "Cheeseburgers",
    "Hot Dogs", "Corn Dogs", "Grilled Cheese Sandwiches", "Chicken Tenders / Fingers",
    "Spaghetti and Meatballs", "Cheese Quesadillas", "Fried Fish / Fish and Chips",
    "Mild Beef Tacos (Hard or Soft Shell)", "Diner Pancakes", "Diner Waffles",
    "French Toast", "Mozzarella Sticks", "Soft Pretzels with Cheese Dip",
    "Onion Rings", "Beef Sliders (Mini Burgers)", "Chicken Fried Rice",
    "Lo Mein Noodles", "Sweet and Sour Chicken", "Chicken Teriyaki Skewers",
    "Edamame", "California Sushi Rolls", "Buttered Pasta with Parmesan",
    "Garlic Bread", "Cheese Ravioli", "Meatball Subs", "Chicken Parmesan",
    "Cheese Nachos", "Bean and Cheese Burritos", "Chicken Fajitas",
    "Crispy Hash Browns", "Chocolate Milkshakes", "Ice Cream Sundaes",
    "Caesar Salad", "Sweet Potato Fries", "Potato Skins", "Popcorn Shrimp",
    "BBQ Ribs", "Pulled Pork Sandwiches", "Deli Macaroni Salad",
    "Deli Potato Salad", "Chicken Noodle Soup", "Tomato Bisque",
    "Restaurant Fruit Cups", "Peanut Butter and Jelly Sandwiches",
    "Boxed Macaroni and Cheese", "Scrambled Eggs", "Hard-boiled Eggs",
    "Goldfish Crackers", "Graham Crackers", "Animal Crackers",
    "Apple Slices with Peanut Butter", "Ants on a Log", "String Cheese / Cheese Sticks",
    "Yogurt Tubes or Cups", "Fruit Gummies / Snacks", "Dry Cereal (e.g., Cheerios)",
    "Oatmeal with Brown Sugar", "Sliced Bananas", "Halved Grapes",
    "Watermelon Chunks", "Fresh Strawberries", "Baby Carrots with Ranch Dip",
    "Cucumber Slices", "Pita Bread with Hummus", "Mini Blueberry Muffins",
    "English Muffin Pizzas", "Pigs in a Blanket", "Homemade Baked Chicken Nuggets",
    "Sloppy Joes", "Baked Tater Tots", "Mashed Potatoes", "Baked Beans",
    "Corn on the Cob", "Buttered Sweet Peas", "Applesauce Cups",
    "Chocolate Pudding", "Jell-O Cups", "Microwave Popcorn",
    "Rice Krispies Treats", "Chewy Granola Bars", "Mini Bagels with Cream Cheese",
    "Cinnamon Sugar Toast", "Homemade Fruit Smoothies",
    "Microwave or Stovetop Quesadillas", "Sliced Meatloaf", "Rotisserie Chicken",
    "Baked Ziti", "Mini Egg Quiches", "Frozen Taquitos", "Potato 'Smiley' Fries",
    "Crepes with Hazelnut Spread", "Homemade S'mores", "Frozen Fruit Popsicles"
].join('\n');
